add_rules("mode.debug", "mode.release")

toolchain("llvm-mingw")
    set_kind("standalone")
    set_toolset("cxx", "clang")
    set_toolset("ld", "clang++")
    set_sdkdir("D:/Program Files/llvm-mingw")
    set_bindir("D:/Program Files/llvm-mingw/bin")
toolchain_end()

set_config("target_os", "windows")
set_toolchains("llvm-mingw")

set_languages("c++latest")
add_cxxflags("-Wall", "-Wextra", "-g", "-fsanitize=address,undefined", "-fno-omit-frame-pointer")
add_ldflags("-fsanitize=address", "-fsanitize=undefined")
set_defaultmode("debug")

add_requires("magic_enum")

target("matoy-syntax")
    set_kind("static")
    add_includedirs("src")
    add_files("src/matoy/syntax/*.cpp")

target("matoy-foundations")
    set_kind("static")
    add_includedirs("src")
    add_files("src/matoy/foundations/*.cpp")

target("matoy-eval")
    set_kind("static")
    add_deps("matoy-foundations")
    add_includedirs("src")
    add_files("src/matoy/eval/*.cpp")

target("matoy-console")
    set_kind("static")
    add_deps("matoy-eval")
    add_includedirs("src")
    add_files("src/matoy/console/*.cpp")
    add_packages("magic_enum", {public = true})
    add_defines("PRETTY", {public = true})

target("matoy")
    set_kind("binary")
    add_deps("matoy-foundations", "matoy-syntax", "matoy-eval", "matoy-console")
    add_includedirs("src")
    add_files("src/*.cpp")

target("test_matrix")
    set_kind("binary")
    add_deps("matoy-foundations")
    add_includedirs("src")
    add_files("tests/test_matrix.cpp")
